# WINDOW GEOMETRY
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600
WINDOW_MIN_WIDTH = 800
WINDOW_MIN_HEIGHT = 600

WINDOW_GEOMETRY = f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}"

# TYPOGRAPHY
FONT_FAMILY = "Segoe UI"

FONT_QUESTION = (FONT_FAMILY, 28, "bold")
FONT_ANSWER = (FONT_FAMILY, 18, "bold")
FONT_FEEDBACK = (FONT_FAMILY, 16, "bold")

FONT_TITLE = (FONT_FAMILY, 24, "bold")
FONT_HEADER = (FONT_FAMILY, 18, "bold")
FONT_SM_HEADER = (FONT_FAMILY, 14, "bold")
FONT_BODY = (FONT_FAMILY, 14)
FONT_DESC = (FONT_FAMILY, 10, "italic")

FONT_HUGE = (FONT_FAMILY, 20)
FONT_LARGE = (FONT_FAMILY, 16)
FONT_MEDIUM = (FONT_FAMILY, 12)
FONT_SMALL = (FONT_FAMILY, 10)
FONT_TINY = (FONT_FAMILY, 8)

FONT_TREEIVEW = (FONT_FAMILY, 12)
FONT_TREEVIEW_BOLD = (FONT_FAMILY, 12, "bold")
FONT_TREEVIEW_HEADING = (FONT_FAMILY, 10, "bold")

FONT_ANSWER_ENTRY = (FONT_FAMILY, 24)

# COLORS
COLOR_SUCCESS = "#196B24"
COLOR_ERROR = "#C00000"

COLOR_RED = "#E74C3C"
COLOR_BLUE = "#3498DB"
COLOR_YELLOW = "#F1C40F"
COLOR_GREEN = "#2ECC71"

COLOR_GRAY = "#A7A7A7"
COLOR_DARK_GRAY = "#6E6E6E"
COLOR_ASH = "#2E2E2E"

COLOR_GOLD = "#D4AF37"
COLOR_SILVER = "#B0B0B0"
COLOR_BRONZE = "#CD7F32"

# MISCELLANEOUS
WRAP_QUESTION = 750
TREEVIEW_ROW_HEIGHT = 30
