"""
connected_client.py

Contains a raw socket wrapper to store additional data related to a networking client, not a game
player. Avoids storing related values to the client in multiple data structures.

This file is not stored in the models directory as it acts more as a runtime object that manages
an active network connection.
"""

import secrets
import socket
import threading
import time

from core.services.network.transport import JSONSocket


class ConnectedClient:
    """
    Acts as a wrapper around a networking socket, that stores data necessary for the server to know about
    a single connected client, relating to the networking state rather than the game state. This object
    can be used to manage communication as well as connection state.

    Arguments:
        client_id: A unique ID to store with this ConnectedClient to uniquely identify it. A string is used
            as it can flexibly store IDs and can store many characters to make them more unique. This can be
            generated by the static method `generate_random_id()`.

        sock: The socket connection that the client uses.

        address: A tuple with the IP address as the first parameter and the ephemeral TCP port as the second,
            detailing the network identity of the client. A tuple is used as that is the format provided by
            the server client accepter.
    """

    def __init__(
        self, client_id: str, sock: socket.socket, address: tuple[str, int]
    ) -> None:
        self.client_id: str = client_id
        self.socket: socket.socket = sock

        # Used to send/receive Python dictionaries directly over the network
        self.jsock = JSONSocket(sock)

        # Network identity of client
        self.ip_address: str = address[0]
        self.port: int = address[1]

        # Reverse DNS hostname of client
        self.hostname: str | None = None

        # When the last ping was sent from the client
        self.last_ping_sent: float | None = None

        # The time it takes between the server sending a PING and the client responding with a PONG
        self.rtt_ms: float | None = None

        # Used for disconnecting dead clients
        self.last_seen: float = time.monotonic()

        # Prevents multiple client threads from sending data at once and becoming mixed
        self._lock = threading.Lock()

    @staticmethod
    def generate_random_id() -> str:
        """
        Generates a random 8-character hexadecimal ID. Since this is a static method, it can be used when
        initializing a ConnectedClient.

        Returns:
            The randomly-generated ID, as a string. A string is used as it can store many characters to make
            them more unique.
        """
        return secrets.token_hex(4)

    def update_last_seen(self) -> None:
        """
        Refreshes the `last_seen` timestamp to the current monotonic time. This method should be run when the
        client sends a message to the server.

        Returns:
            None.
        """
        self.last_seen = time.monotonic()

    def send(self, msg: dict) -> None:
        """
        Sends a dictionary to the client, by converting it to JSON before sending.

        Uses a threading lock to avoid corruption from multiple threads sending a message at once, meaning
        it should not be run inside another method that holds the lock to avoid deadlocks.

        Arguments:
            msg: The dictionary to send to the client. A dictionary is used as it can store multiple values
                in one data type, and be easily serialized and deserialized into JSON and back.

        Returns:
            None.
        """
        # Lock to prevent multiple concurrent sends overwriting each other
        with self._lock:
            self.jsock.send(msg)

    def recv(self) -> dict | bool | None:
        """
        Receives the next JSON message from the client, and converts it to a dictionary before returning.

        Returns:
            A dictionary containing data sent from the client if the data was successfully received and parsed.
            Returns None if the connection was closed, or False if the connection timed out but is still open.
        """
        return self.jsock.recv()

    def close(self) -> None:
        """
        Closes the client socket network connection. If the socket has already been closed, ignores it.

        Uses a threading lock to avoid errors from closing while sending messages, meaning it should not be run
        inside another method that holds the lock to avoid deadlocks.

        Returns:
            None.
        """
        with self._lock:
            try:
                self.socket.close()
            except OSError:
                # If the socket has already been closed
                pass
