from enum import Enum


class Screens(Enum):
    # Client
    CLIENT_SETUP = "CLIENT_SETUP"
    CLIENT_LOBBY = "CLIENT_LOBBY"
    CLIENT_MULTI_QUESTION = "CLIENT_MULTI_QUESTION"
    CLIENT_MULTI_RESULT = "CLIENT_MULTI_RESULT"
    CLIENT_FINAL_RESULT = "CLIENT_FINAL_RESULT"
    CLIENT_DISCONNECT = "CLIENT_DISCONNECT"

    # Server
    SERVER_LOBBY = "SERVER_LOBBY"
    SERVER_MULTI_QUESTION = "SERVER_MULTI_QUESTION"
    SERVER_MULTI_RESULT = "SERVER_MULTI_RESULT"
    SERVER_FINAL_RESULT = "SERVER_FINAL_RESULT"

    # Common
    COMMON_MENU = "COMMON_MENU"
    COMMON_LOADING = "COMMON_LOADING"
    COMMON_COUNTDOWN = "COMMON_COUNTDOWN"
    COMMON_ABOUT = "COMMON_ABOUT"
