"""
question.py

Defines a single question, which is typically stored within a Quiz.
"""

import secrets
from dataclasses import asdict, dataclass

from core.app.enums import QuestionValidationError
from core.config.constants import MAX_ANSWER_LENGTH, MAX_QUESTION_LENGTH


@dataclass
class Question:
    """
    Creates a new Question instance, which stores details about a single question within a Quiz. Use
    a Question to store questions in a Quiz to avoid working with raw dictionaries, which can provide
    poor type checks and no helper methods. A Question is typically stored within a Quiz.

    Arguments:
        question_id: A string describing the ID that should be used to uniquely identify this question.
            A string is used as it can flexibly store IDs and can store many characters to make them
            more unique. This can be generated by the static method `generate_random_id()`.

        question_text: A string containing the text of the question to display to the user, for them to
            answer. A string is used as it can store a large length of varying characters.

        answer_options: A list of strings that should be between 2-4 values, each containing a possible
            answer for the question described. At least one of the values should be correct; the rest can
            be incorrect. A list is used as it orders the answers and groups the similar values together.

        correct_answer_index: The index of the correct answer, as a zero-based index respective to the
            `answer_options` list, ranging from 0 to the number of valid answers, minus 1. An integer
            is used as it can easily identify an index in an iterable.

        time_limit: The time limit for answering this question, in seconds. The value should be any
            positive value; not a negative value or 0. An integer is used as the seconds do not need to
            have further precision.
    """

    question_id: str
    question_text: str
    answer_options: list[str]
    correct_answer_index: int | None
    time_limit: int

    @staticmethod
    def generate_random_id() -> str:
        """
        Generates a random 8-character hexadecimal ID. Since this is a static method, it can be used when
        initializing a Question.

        Returns:
            The randomly-generated ID, as a string. A string is used as it can store many characters to make
            them more unique.
        """
        return secrets.token_hex(4)

    def remove_empty_answers(self, mutate_answers: bool = True) -> list[str]:
        """
        Removes empty answer options that are empty or only contain whitespace. This should only be run when
        it is confirmed that the first two answers are not blank, to avoid shifting positions incorrectly.

        Arguments:
            mutate_answers: A boolean deciding whether or not to update the instance's `answer_options`
                attribute and save the changes. Defaults the mutating the instance's `answer_options` by setting
                it to True, otherwise, returns the new answers list without any empty answers, without updating the
                answer options.

        Returns:
            The new list of answers without any empty answers. This is always returned, even if the `answer_options`
            is mutated.
        """
        non_empty_answers = [a.strip() for a in self.answer_options if a.strip() != ""]

        if mutate_answers:
            self.answer_options = non_empty_answers

        return non_empty_answers

    def validate_question(self) -> set[QuestionValidationError]:
        """
        Validates only this question for any issues. Only checks for issues that can be done through the
        application, for example, the quiz editor. Therefore, this can be used to find any errors with the
        question while editing live, and inform the user of what the question needs refactoring before
        deemed complete.

        Errors that are based on invalid values that aren't possible through the application (e.g. invalid
        ID type) are validated by the Quiz instead.

        The following conditions are checked:
        - Whether the question text is empty.
        - Whether the question text exceeds the maximum limit of characters.
        - Whether there are at least two answers and both of the first two answers have text.
        - Whether any of the answer texts exceeds the maximum limit of characters.
        - Whether there are any duplicate answer options.
        - Whether a correct answer has been selected.

        Returns:
            A set containing any and all issues that were found by validating the question, with
            `QuestionValidationErrors` identifying the errors. The set is empty if no issues were found.
            A set is used to store multiple errors at once, and also to prevent duplicate errors.
        """
        errors: set[QuestionValidationError] = set()

        question_text = self.question_text.strip()
        answer_options = [a.strip() for a in self.answer_options]
        non_empty_answers = self.remove_empty_answers(mutate_answers=False)

        if not question_text:
            errors.add(QuestionValidationError.MISSING_QUESTION)

        if len(question_text) > MAX_QUESTION_LENGTH:
            errors.add(QuestionValidationError.QUESTION_TOO_LONG)

        # At least two answers, and the first two answers are required to not be empty
        if len(answer_options) < 2 or not answer_options[0] or not answer_options[1]:
            errors.add(QuestionValidationError.MISSING_REQUIRED_ANSWERS)

        # If any of the answers exceeds the limit
        if any(len(answer) > MAX_ANSWER_LENGTH for answer in answer_options):
            errors.add(QuestionValidationError.ANSWER_TOO_LONG)

        if len(non_empty_answers) != len(set(non_empty_answers)):
            errors.add(QuestionValidationError.DUPLICATE_ANSWER)

        if self.correct_answer_index is None:
            errors.add(QuestionValidationError.NO_CORRECT_ANSWER)

        return errors

    def to_dict(self) -> dict:
        """
        Converts the question to a dictionary. Useful for serialization for saving the quiz.

        Returns:
            The Question converted to a dictionary.
        """
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "Question":
        """
        Converts a dictionary to a Question. Useful for deserializing data from a save file.

        Arguments:
            data: The dictionary to convert to the Question object.

        Returns:
            The newly-created question object from the dictionary provided.

        Raises:
            ValueError: If the dictionary provided did not follow the question format.
        """
        try:
            # Use .get() rather than **data to avoid the field not existing and throwing an error
            return cls(
                question_id=data.get("question_id"),
                question_text=data.get("question_text"),
                answer_options=data.get("answer_options"),
                correct_answer_index=data.get("correct_answer_index"),
                time_limit=data.get("time_limit"),
            )
        except TypeError as e:
            raise ValueError(f"Invalid format: {e}") from e
