"""
quiz.py

Defines a whole quiz, containing metadata relating to it as a whole as well containing all the
questions.
"""

import random
import secrets
from dataclasses import asdict, dataclass
from datetime import datetime

from core.app.enums import QuizValidationError
from models.question import Question


@dataclass
class Quiz:
    """
    Creates a new Quiz instance, which stores details about an entire quiz, including storing individual
    Questions within.

    Arguments:
        quiz_id: A string describing the ID that should be used to uniquely identify this quiz.
            A string is used as it can flexibly store IDs and can store many characters to make them
            more unique. This can be generated by the static method `generate_random_id()`.

        quiz_title: A string containing the title of the quiz to identify it in a user-friendly way. A
            string is used as it can store a large length of varying characters.

        questions: A list of Questions that the quiz contains, in the order they were provided in. A
            list is used as it orders the questions and groups the same data types together.

        do_shuffle: Whether to shuffle the questions when playing the quiz. This shuffles the order of
            the questions in this Quiz instance directly. True to shuffle questions, else, False. A
            boolean is used as it is naturally a binary statement.

        is_premade: Whether to shuffle the questions when playing the quiz. This shuffles the order of
            the questions in this Quiz instance directly. True to shuffle questions, else, False. A
            boolean is used as it is naturally a binary statement.

        is_complete: Whether the quiz is complete (meaning it has no errors preventing it from being
            played). True if the quiz is complete and ready to play, else, False if the quiz has errors.
            A boolean is used as it is naturally a binary statement.

        updated_at: The date and time the quiz was last updated in its save file. Can also be None if
            the quiz is a pre-made quiz. A datetime is used as it can easily store more data relating
            to the date and time it was saved. Defaults to None.
    """

    quiz_id: str
    quiz_title: str
    questions: list[Question]
    do_shuffle: bool
    is_premade: bool
    is_complete: bool
    updated_at: datetime | None = None

    @staticmethod
    def generate_random_id() -> str:
        """
        Generates a random 8-character hexadecimal ID. Since this is a static method, it can be used when
        initializing a Quiz.

        Returns:
            The randomly-generated ID, as a string. A string is used as it can store many characters to make
            them more unique.
        """
        return secrets.token_hex(4)

    def add_question(self, question: Question, index: int | None = None) -> int:
        """
        Adds a new question to the quiz, as a Question. If the index is not specified, adds the question to
        the end of the question list. Otherwise, if the index is specified, the question is inserted at that
        position and all further questions are shifted by one.

        Arguments:
            question: The Question instance to add to the questions list of the quiz. A Question instance is
                used as it allows easier storage of it without using dictionaries.

            index: The zero-based index to insert the question at in the questions list, or None. If set to
                None, the question is automatically inserted at the end of the questions list. Otherwise, it
                is added to the position specified. An integer is used as it easily specifies list positions.
                Default is None.

        Returns:
            The index that the question was inserted at, as a zero-based integer index.
        """
        if index is None:
            self.questions.append(question)
            return len(self.questions) - 1
        else:
            self.questions.insert(index, question)
            return index

    def remove_question(self, question_id: str) -> None:
        """
        Removes the first occurrence of the specified question from the questions list, identified by its
        question ID.

        Arguments:
            question_id: A string describing the ID of the Question instance to remove. A string is used as it
                can flexibly store IDs and can store many characters to make them more unique.

        Returns:
            None.
        """
        for i, question in enumerate(self.questions):
            if question.question_id == question_id:
                # Only deletes the first occurrence, then exits
                del self.questions[i]
                break

    def get_question(self, index: int) -> Question:
        """
        Retrieve a Question from the given `index` in the quiz. The index is not the question number, and is
        a zero-based index corresponding to the respective question stored in the Quiz. Negative indexes are
        disallowed.

        Arguments:
            index: The index of the question position in the Quiz, as a non-negative integer. The maximum value
                allowed is the number of questions in the quiz minus one. An integer is used as it is used
                for indexing in lists.

        Returns:
            The Question at the provided index.

        Raises:
            IndexError: If the question index provided is out of range. Negative indexes are disallowed and they
                must not exceed the length of the questions list.
        """
        if not 0 <= index < len(self.questions):
            raise IndexError(f"Question index {index} is out of range")

        return self.questions[index]

    def get_question_index(self, question_id: str) -> int | None:
        """
        Gets the index of the specified question by question ID, returning its zero-based index on the list,
        if it exists.

        Arguments:
            question_id: A string describing the ID of the Question instance to locate. A string is used as it
                can flexibly store IDs and can store many characters to make them more unique.

        Returns:
            The index of the question as an integer, starting from 0 and extending until the end of the question
            list minus one. Returns None if the question could not be found. An integer is used as it can be used
            for indexing.
        """
        for i, question in enumerate(self.questions):
            if question.question_id == question_id:
                return i

        return None

    def get_total_questions(self) -> int:
        """
        Gets the total number of questions in the quiz currently.

        Returns:
            The number of questions in the quiz, as an integer, since the number of elements is represented
            easily as a whole number.
        """
        return len(self.questions)

    def shuffle_questions(self) -> None:
        """
        Randomly shuffles the questions in the quiz, while mutating the questions list. Only works if the
        `do_shuffle` property is True, otherwise, this method does nothing.

        Returns:
            None.
        """
        if self.do_shuffle:
            random.shuffle(self.questions)

    def move_question(self, question_id: str, new_index: int) -> None:
        """
        Manually moves a question from one position to the new specified index. Moves questions around it
        to adapt to the new question index.

        For example, if you have:
        | 0  | 1  | 2  | 3  |
        |----|----|----|----|
        | Q1 | Q2 | Q3 | Q4 |

        And you want to move Q1 to index 2:
        | 0  | 1  | 2  | 3  |
        |----|----|----|----|
        | Q2 | Q3 | Q1 | Q4 |

        Arguments:
            question_id: A string describing the ID of the Question instance to move. A string is used as it
                can flexibly store IDs and can store many characters to make them more unique.

            new_index: The new zero-based index to move the question specified to. This should be in a valid
                range of the questions list. An integer is used as that is what indexes use.

        Returns:
            None.
        """
        # Get the question index on the first question ID match, or None if there were no matches
        old_index = next(
            (i for i, q in enumerate(self.questions) if q.question_id == question_id),
            None,
        )

        if old_index is None:
            return

        # Remove and retrieve question from original position, then add it again
        question = self.questions.pop(old_index)
        self.questions.insert(new_index, question)

    def validate_quiz(self, critical_only: bool = False) -> set[QuizValidationError]:
        """
        Validates the quiz for any issues, including some values of the questions it contained. Only checks
        for issues that can not be done through the application, and can only be done through file corruption
        or deliberate tampering of the save file by the user. Therefore, this should be used to find any
        errors before using the Quiz instance, to ensure the application does not crash, and show warnings or
        errors to the user, if necessary.

        To check for question-specific errors that are possible through the application, use
        `Question.validate_question()`.

        Some checks are only performed when `critical_only` is False. The following conditions are checked:
        - Whether the quiz ID is empty or not a string.
        - Whether the quiz title is empty or not a string.
        - Whether the questions are filled in. Not checked when performing critical-only checks.
        - Whether the shuffling information is a boolean.
        - Whether the pre-made quiz information is a boolean.
        - Whether the completeness information is a boolean.
        - For any question, whether the question ID is a string.
        - For any question, whether the question ID has been used more than once.
        - For any question, whether the question text is a string.
        - For any question, whether the answer options is a list.
        - For any question, whether the correct answer index is an integer and within the valid range. Not
          checked when performing critical-only checks.
        - For any question, whether the time limit is an integer and a positive integer.

        Arguments:
            critical_only: Whether to skip some tests, mainly ones that are normal to encounter during the
                creation of a quiz. The tests that are skipped are listed above. By default, this is set to
                False, meaning every check is run. When True, only some tests are run.

        Returns:
            A set containing any and all issues that were found by validating the quiz, with
            `QuizValidationErrors` identifying the errors. The set is empty if no issues were found. A set is
            used to store multiple errors at once, and also to prevent duplicate errors.
        """
        errors: set[QuizValidationError] = set()
        seen_question_ids: set[str] = set()

        # General quiz metadata information validation
        if not self.quiz_id or not isinstance(self.quiz_id, str):
            errors.add(QuizValidationError.MISSING_ID)

        if not self.quiz_title or not isinstance(self.quiz_title, str):
            errors.add(QuizValidationError.MISSING_TITLE)

        # Only checks if non-critical checks allowed
        if not critical_only and not self.questions:
            errors.add(QuizValidationError.MISSING_QUESTIONS)

        if not isinstance(self.do_shuffle, bool):
            errors.add(QuizValidationError.NO_SHUFFLE_INFO)

        if not isinstance(self.is_premade, bool):
            errors.add(QuizValidationError.NO_PREMADE_INFO)

        if not isinstance(self.is_complete, bool):
            errors.add(QuizValidationError.NO_COMPLETENESS_INFO)

        # Individual question validation
        for question in self.questions:
            if not isinstance(question.question_id, str):
                errors.add(QuizValidationError.INVALID_QUESTION_ID)

            if question.question_id in seen_question_ids:
                errors.add(QuizValidationError.DUPLICATED_QUESTION_ID)

            # Add current question ID for next iteration
            seen_question_ids.add(question.question_id)

            if not isinstance(question.question_text, str):
                errors.add(QuizValidationError.INVALID_QUESTION_TEXT)

            if not isinstance(question.answer_options, list):
                errors.add(QuizValidationError.INVALID_ANSWERS)

            # Only checks if non-critical checks allowed.
            # Checks if the correct answer index is out of the range for the
            # amount of answers. For example, if the correct answer index is 4
            # when question indexes are only 0-3.
            if not critical_only and (
                not isinstance(question.correct_answer_index, int)
                or not 0
                <= int(question.correct_answer_index)
                < len(question.answer_options)
            ):
                errors.add(QuizValidationError.INVALID_CORRECT_ANSWER)

            if not isinstance(question.time_limit, int) or question.time_limit <= 0:
                errors.add(QuizValidationError.INVALID_TIME)

        return errors

    def to_dict(self) -> dict:
        """
        Converts the quiz to a dictionary. Useful for serialization for saving the quiz.

        The updated at time is saved in ISO format with seconds precision.

        Returns:
            The Quiz converted to a dictionary.
        """
        data = asdict(self)

        if self.updated_at is not None:
            # Avoid saving microseconds using timespec="seconds"
            data["updated_at"] = self.updated_at.isoformat(timespec="seconds")

        return data

    @classmethod
    def from_dict(cls, data: dict) -> "Quiz":
        """
        Converts a dictionary to a Quiz. Useful for deserializing data from a save file.

        Arguments:
            data: The dictionary to convert to the Quiz object.

        Returns:
            The newly-created quiz object from the dictionary provided.

        Raises:
            ValueError: If the dictionary provided did not follow the quiz format.
        """
        updated_at = data.get("updated_at")

        try:
            # Try converting the saved date, if valid
            if updated_at is not None:
                updated_at = datetime.fromisoformat(updated_at)
        except (TypeError, ValueError):
            updated_at = None

        # If questions is not a list, Question.from_dict() will crash
        questions = data.get("questions")
        if not isinstance(questions, list):
            questions = []

        try:
            # Use .get() rather than direct keys to avoid the field not existing and throwing an error
            return cls(
                quiz_id=data.get("quiz_id"),
                quiz_title=data.get("quiz_title"),
                questions=[Question.from_dict(q) for q in questions],
                do_shuffle=data.get("do_shuffle"),
                is_premade=data.get("is_premade"),
                is_complete=data.get("is_complete"),
                updated_at=updated_at,
            )
        except TypeError as e:
            raise ValueError(f"Invalid format: {e}") from e
